version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=casino_roulettes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwesaR29
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    volumes: 
      - ./redis_data:/var/lib/redis/data